// Code generated by ogen, DO NOT EDIT.

package spec

// setDefaults set default value of fields.
func (s *AddReadContext) setDefaults() {
	{
		val := bool(false)
		s.DisableReadLogging.SetTo(val)
	}
	{
		val := int32(0)
		s.KeyCacheTTL.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CapabilityDefinition) setDefaults() {
	{
		val := bool(false)
		s.Unary = val
	}
}

// setDefaults set default value of fields.
func (s *CapsuleOpenResponseReadContextConfiguration) setDefaults() {
	{
		val := bool(false)
		s.DisableReadLogging.SetTo(val)
	}
	{
		val := int32(0)
		s.KeyCacheTTL.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreatePeerDomain) setDefaults() {
	{
		val := bool(false)
		s.LinkAll.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkIdentityProviders.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkFacts.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkReadContexts.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkWriteContexts.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkCapabilities.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkDomainPolicy.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkRootEncryptionKeys.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkCapsuleAccessLog.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkControlLog.SetTo(val)
	}
	{
		val := bool(false)
		s.LinkCapsuleManifest.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FactPolicyRulesItemArgumentsItem) setDefaults() {
	{
		val := bool(false)
		s.Any.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *NewCapabilityDefinition) setDefaults() {
	{
		val := bool(false)
		s.Unary = val
	}
}

// setDefaults set default value of fields.
func (s *ReadContextDetails) setDefaults() {
	{
		val := bool(false)
		s.DisableReadLogging.SetTo(val)
	}
	{
		val := int32(0)
		s.KeyCacheTTL.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ReadContextShortDetails) setDefaults() {
	{
		val := bool(false)
		s.DisableReadLogging.SetTo(val)
	}
	{
		val := int32(0)
		s.KeyCacheTTL.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WriteContextConfigInfo) setDefaults() {
	{
		val := int32(0)
		s.KeyReuseTTL.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WriteContextConfigInfoRequiredHooksItem) setDefaults() {
	{
		val := WriteContextConfigInfoRequiredHooksItemMode("sync")
		s.Mode = val
	}
}
