// Code generated by ogen, DO NOT EDIT.
package spec

type CapsuleGetByIdRes interface {
	capsuleGetByIdRes()
}

type DomainAddAccessLogEntryRes interface {
	domainAddAccessLogEntryRes()
}

type DomainAddExternalRootEncryptionKeyRes interface {
	domainAddExternalRootEncryptionKeyRes()
}

type DomainAddNewRes interface {
	domainAddNewRes()
}

type DomainAddPeerDomainRes interface {
	domainAddPeerDomainRes()
}

type DomainAuthenticateRes interface {
	domainAuthenticateRes()
}

type DomainContactIssueVerifyRes interface {
	domainContactIssueVerifyRes()
}

type DomainContactVerifyRes interface {
	domainContactVerifyRes()
}

type DomainCreateCapsuleRes interface {
	domainCreateCapsuleRes()
}

type DomainCreateDataPolicyRes interface {
	domainCreateDataPolicyRes()
}

type DomainCreatePolicyRuleRes interface {
	domainCreatePolicyRuleRes()
}

type DomainDataPolicyConfigureRulesRes interface {
	domainDataPolicyConfigureRulesRes()
}

type DomainDataPolicyRuleUpdateRes interface {
	domainDataPolicyRuleUpdateRes()
}

type DomainDataTaggingHookInvokeRes interface {
	domainDataTaggingHookInvokeRes()
}

type DomainDataTaggingHookTestRes interface {
	domainDataTaggingHookTestRes()
}

type DomainDeleteCapabilityRes interface {
	domainDeleteCapabilityRes()
}

type DomainDeleteCapsuleTagsRes interface {
	domainDeleteCapsuleTagsRes()
}

type DomainDeleteDataPolicyRes interface {
	domainDeleteDataPolicyRes()
}

type DomainDeleteDataPolicyRuleRes interface {
	domainDeleteDataPolicyRuleRes()
}

type DomainDeleteExternalRootEncryptionKeyRes interface {
	domainDeleteExternalRootEncryptionKeyRes()
}

type DomainDeleteFactByIDRes interface {
	domainDeleteFactByIDRes()
}

type DomainDeleteFactTypeRes interface {
	domainDeleteFactTypeRes()
}

type DomainDeleteIdentityProviderPrincipalRes interface {
	domainDeleteIdentityProviderPrincipalRes()
}

type DomainDeleteIdentityProviderRes interface {
	domainDeleteIdentityProviderRes()
}

type DomainDeletePeerRes interface {
	domainDeletePeerRes()
}

type DomainDeletePolicyRuleRes interface {
	domainDeletePolicyRuleRes()
}

type DomainDeleteReadContextRes interface {
	domainDeleteReadContextRes()
}

type DomainDeleteWriteContextClassifierRuleRes interface {
	domainDeleteWriteContextClassifierRuleRes()
}

type DomainDeleteWriteContextRegexRuleRes interface {
	domainDeleteWriteContextRegexRuleRes()
}

type DomainDeleteWriteContextRes interface {
	domainDeleteWriteContextRes()
}

type DomainDescribeWriteContextRes interface {
	domainDescribeWriteContextRes()
}

type DomainExternalRootEncryptionKeyTestRes interface {
	domainExternalRootEncryptionKeyTestRes()
}

type DomainFlushEncryptionKeysRes interface {
	domainFlushEncryptionKeysRes()
}

type DomainGetActiveExternalRootEncryptionKeyRes interface {
	domainGetActiveExternalRootEncryptionKeyRes()
}

type DomainGetCapabilitiesRes interface {
	domainGetCapabilitiesRes()
}

type DomainGetCapabilityRes interface {
	domainGetCapabilityRes()
}

type DomainGetCapsuleInfoRes interface {
	domainGetCapsuleInfoRes()
}

type DomainGetDataPolicyBindingRes interface {
	domainGetDataPolicyBindingRes()
}

type DomainGetDataPolicyRes interface {
	domainGetDataPolicyRes()
}

type DomainGetDataPolicyRuleRes interface {
	domainGetDataPolicyRuleRes()
}

type DomainGetDisasterRecoverySettingsRes interface {
	domainGetDisasterRecoverySettingsRes()
}

type DomainGetExternalRootEncryptionKeyProvidersRes interface {
	domainGetExternalRootEncryptionKeyProvidersRes()
}

type DomainGetFactByIDRes interface {
	domainGetFactByIDRes()
}

type DomainGetFactTypeRes interface {
	domainGetFactTypeRes()
}

type DomainGetIdentityProviderPrincipalRes interface {
	domainGetIdentityProviderPrincipalRes()
}

type DomainGetIdentityProviderPrincipalsRes interface {
	domainGetIdentityProviderPrincipalsRes()
}

type DomainGetIdentityProviderRes interface {
	domainGetIdentityProviderRes()
}

type DomainGetPeerConfigRes interface {
	domainGetPeerConfigRes()
}

type DomainGetPeerRes interface {
	domainGetPeerRes()
}

type DomainGetPrivateInfoRes interface {
	domainGetPrivateInfoRes()
}

type DomainGetPublicInfoRes interface {
	domainGetPublicInfoRes()
}

type DomainGetReadContextRes interface {
	domainGetReadContextRes()
}

type DomainGetSettingsRes interface {
	domainGetSettingsRes()
}

type DomainGetStatusRes interface {
	domainGetStatusRes()
}

type DomainGetTagInfoRes interface {
	domainGetTagInfoRes()
}

type DomainGetVendorSettingsRes interface {
	domainGetVendorSettingsRes()
}

type DomainGetWriteContextClassifierRulesRes interface {
	domainGetWriteContextClassifierRulesRes()
}

type DomainGetWriteContextRegexRulesRes interface {
	domainGetWriteContextRegexRulesRes()
}

type DomainInsertIdentityProviderPrincipalRes interface {
	domainInsertIdentityProviderPrincipalRes()
}

type DomainInsertWriteContextClassifierRuleRes interface {
	domainInsertWriteContextClassifierRuleRes()
}

type DomainInsertWriteContextRegexRuleRes interface {
	domainInsertWriteContextRegexRuleRes()
}

type DomainListCapsulesRes interface {
	domainListCapsulesRes()
}

type DomainListDataPoliciesRes interface {
	domainListDataPoliciesRes()
}

type DomainListExternalRootEncryptionKeyRes interface {
	domainListExternalRootEncryptionKeyRes()
}

type DomainListFactTypesRes interface {
	domainListFactTypesRes()
}

type DomainListFactsRes interface {
	domainListFactsRes()
}

type DomainListHooksRes interface {
	domainListHooksRes()
}

type DomainListIdentityProvidersRes interface {
	domainListIdentityProvidersRes()
}

type DomainListPeersRes interface {
	domainListPeersRes()
}

type DomainListPolicyRulesRes interface {
	domainListPolicyRulesRes()
}

type DomainListReadContextsRes interface {
	domainListReadContextsRes()
}

type DomainListResourcesRes interface {
	domainListResourcesRes()
}

type DomainListWriteContextsRes interface {
	domainListWriteContextsRes()
}

type DomainOpenCapsuleRes interface {
	domainOpenCapsuleRes()
}

type DomainPolicyFlushRes interface {
	domainPolicyFlushRes()
}

type DomainPutCapabilityRes interface {
	domainPutCapabilityRes()
}

type DomainPutDisasterRecoverySettingsRes interface {
	domainPutDisasterRecoverySettingsRes()
}

type DomainPutFactTypeRes interface {
	domainPutFactTypeRes()
}

type DomainPutSettingsRes interface {
	domainPutSettingsRes()
}

type DomainPutVendorSettingsRes interface {
	domainPutVendorSettingsRes()
}

type DomainQueryAccessLogRes interface {
	domainQueryAccessLogRes()
}

type DomainQueryAccessLogSingleCapsuleRes interface {
	domainQueryAccessLogSingleCapsuleRes()
}

type DomainQueryControlLogRes interface {
	domainQueryControlLogRes()
}

type DomainRenumberDataPolicyRulesRes interface {
	domainRenumberDataPolicyRulesRes()
}

type DomainRenumberPolicyRulesRes interface {
	domainRenumberPolicyRulesRes()
}

type DomainRotateRootEncryptionKeysRes interface {
	domainRotateRootEncryptionKeysRes()
}

type DomainSealCapsuleRes interface {
	domainSealCapsuleRes()
}

type DomainSetActiveExternalRootEncryptionKeyRes interface {
	domainSetActiveExternalRootEncryptionKeyRes()
}

type DomainSetDataPolicyBindingRes interface {
	domainSetDataPolicyBindingRes()
}

type DomainUpdateDataPolicyRes interface {
	domainUpdateDataPolicyRes()
}

type DomainUpdateIdentityProviderPrincipalRes interface {
	domainUpdateIdentityProviderPrincipalRes()
}

type DomainUpdatePeerRes interface {
	domainUpdatePeerRes()
}

type DomainUpdatePolicyRuleRes interface {
	domainUpdatePolicyRuleRes()
}

type DomainUpsertCapsuleTagsRes interface {
	domainUpsertCapsuleTagsRes()
}

type DomainUpsertFactRes interface {
	domainUpsertFactRes()
}

type DomainUpsertIdentityProviderRes interface {
	domainUpsertIdentityProviderRes()
}

type DomainUpsertReadContextRes interface {
	domainUpsertReadContextRes()
}

type DomainUpsertSpanTagsRes interface {
	domainUpsertSpanTagsRes()
}

type DomainUpsertWriteContextConfigurationRes interface {
	domainUpsertWriteContextConfigurationRes()
}

type DomainUpsertWriteContextRes interface {
	domainUpsertWriteContextRes()
}

type StarredDomainAddRes interface {
	starredDomainAddRes()
}

type StarredDomainListRes interface {
	starredDomainListRes()
}

type StarredDomainRemoveRes interface {
	starredDomainRemoveRes()
}
